### ISSUE TITLE
Kinect not working with Ubuntu 12.04

### ISSUE THREAD

**Issue by bitcraze-issue-importer** [bitcraze/crazyflie-clients-python#100]
There seems to be a problem using the Kinect on Ubuntu 12.04, updating to 13.10 solves the issue. The Kinect was connected via USB3.

```
#!

send_cmd: Bad magic 00 7a
freenect_fetch_reg_pad_info: send_cmd read -1 bytes (expected 8)
freenect_camera_init(): Failed to fetch registration pad info for device
Error: Invalid index [0]
Error: Can't open device. 1.) is it plugged in? 2.) Read the README
send_cmd: Bad len 0004 != 001c
freenect_fetch_reg_pad_info: send_cmd read -1 bytes (expected 8)
freenect_camera_init(): Failed to fetch registration pad info for device
Error: Invalid index [0]
Error: Can't open device. 1.) is it plugged in? 2.) Read the README
Traceback (most recent call last):
  File "./cfkinect", line 85, in <module>
    cfkinect.main()
  File "/home/veerachart/Research/Crazyflie/CFKinect/crazyflie-pc-client/lib/cfkinect.py", line 171, in main
    kinect_pilot.control(args.dry)
  File "/home/veerachart/Research/Crazyflie/CFKinect/crazyflie-pc-client/lib/cfkinect.py", line 97, in control
    (x,y,depth) = self.kinect.find_position()
  File "/home/veerachart/Research/Crazyflie/CFKinect/crazyflie-pc-client/lib/kinect/kinect.py", line 159, in find_position
    (kinect_depth,_), (rgb,_) = get_depth(), get_video()
TypeError: 'NoneType' object is not iterable
```

This was reported in the [forum](http://forum.bitcraze.se/viewtopic.php?f=5&t=707&p=4323#p4323)

---------------------------------------
- Bitbucket: https://bitbucket.org/bitcraze/crazyflie-pc-client/issue/100
- Originally Reported By: [Marcus Eliasson](http://bitbucket.org/MackeE)
- Originally Created At: 2014-01-21T11:18:50.180

**Comment by evoggy** [comment]
There's a new LTS version available and this could not be reproduced on that version.
