### ISSUE TITLE
Cannot run cfclient on Linux, installed paths are incorrect

### ISSUE THREAD

**Issue by krystian-wojtas** [bitcraze/crazyflie-clients-python#237]
I have Ubuntu 14.04, python 3.4. I installed all the dependencies and I can run cfclient from master branch. But on develop branch I cannot run cfclient:

$ sudo python3 setup.py install
...
$ ./bin/cfclient
INFO:cfclient.gui:Disabling STL printouts
Traceback (most recent call last):
  File "./bin/cfclient", line 5, in <module>
    main()
  File "/usr/local/lib/python3.4/dist-packages/cfclient-_modified-py3.4.egg/cfclient/gui.py", line 135, in main
    from .ui.main import MainUI
  File "/usr/local/lib/python3.4/dist-packages/cfclient-_modified-py3.4.egg/cfclient/ui/main.py", line 33, in <module>
    import cfclient.ui.tabs
  File "/usr/local/lib/python3.4/dist-packages/cfclient-_modified-py3.4.egg/cfclient/ui/tabs/__init__.py", line 33, in <module>
    from .ConsoleTab import ConsoleTab
  File "/usr/local/lib/python3.4/dist-packages/cfclient-_modified-py3.4.egg/cfclient/ui/tabs/ConsoleTab.py", line 48, in <module>
    "/ui/tabs/consoleTab.ui")[0]
  File "/usr/lib/python3/dist-packages/PyQt4/uic/__init__.py", line 210, in loadUiType
    winfo = compiler.UICompiler().compileUi(uifile, code_string, from_imports, resource_suffix)
  File "/usr/lib/python3/dist-packages/PyQt4/uic/Compiler/compiler.py", line 139, in compileUi
    w = self.parse(input_stream, resource_suffix)
  File "/usr/lib/python3/dist-packages/PyQt4/uic/uiparser.py", line 943, in parse
    document = parse(filename)
  File "/usr/lib/python3.4/xml/etree/ElementTree.py", line 1187, in parse
    tree.parse(source, parser)
  File "/usr/lib/python3.4/xml/etree/ElementTree.py", line 587, in parse
    source = open(source, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.4/dist-packages/cfclient-_modified-py3.4.egg/cfclient/ui/tabs/consoleTab.ui'

A workaround is to manually copy ui directory one up:
`$ sudo cp -r /usr/local/lib/python3.4/dist-packages/cfclient-_modified-py3.4.egg/ui/ /usr/local/lib/python3.4/dist-packages/cfclient-_modified-py3.4.egg/cfclient/`

Then there is another similar error:
$ ./bin/cfclient 
INFO:cfclient.gui:Disabling STL printouts
INFO:cfclient.utils.input.inputreaders:Found readers: ['pysdl2', 'linuxjsdev']
INFO:cfclient.utils.input.inputreaders:Could not initialize [pysdl2]: No SDL2 support on Linux
INFO:cfclient.utils.input.inputreaders:Successfully initialized [linuxjsdev]
INFO:cfclient.utils.input.inputinterfaces:Found interfaces: ['wiimote', 'leapmotion', 'zmqpull']
INFO:cfclient.utils.input.inputinterfaces:Could not initialize [wiimote]: Missing cwiid (wiimote) driver No module named 'cwiid'
INFO:cfclient.utils.input.inputinterfaces:Could not initialize [leapmotion]: Leap Motion library probably not installed (No module named 'leapsdk')
INFO:cfclient.utils.input.inputinterfaces:Could not initialize [zmqpull]: [Errno 2] No such file or directory: '/usr/local/lib/python3.4/dist-packages/cfclient-_modified-py3.4.egg/cfclient/configs/config.json'
===== 2016.03.08 10:03:07 =====
Traceback (most recent call last):
  File "./bin/cfclient", line 5, in <module>
    main()
  File "/usr/local/lib/python3.4/dist-packages/cfclient-_modified-py3.4.egg/cfclient/gui.py", line 152, in main
    main_window = MainUI()
  File "/usr/local/lib/python3.4/dist-packages/cfclient-_modified-py3.4.egg/cfclient/ui/main.py", line 175, in __init__
    cflib.crtp.init_drivers(enable_debug_driver=Config()
  File "/usr/local/lib/python3.4/dist-packages/cfclient-_modified-py3.4.egg/cfclient/utils/singleton.py", line 45, in __call__
    *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/cfclient-_modified-py3.4.egg/cfclient/utils/config.py", line 52, in __init__
    [self._readonly, self._data] = self._read_distfile()
  File "/usr/local/lib/python3.4/dist-packages/cfclient-_modified-py3.4.egg/cfclient/utils/config.py", line 60, in _read_distfile
    f = open(self._dist_config, 'r')
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.4/dist-packages/cfclient-_modified-py3.4.egg/cfclient/configs/config.json'

Another workaround:
`$ sudo cp -r /usr/local/lib/python3.4/dist-packages/cfclient-_modified-py3.4.egg/configs /usr/local/lib/python3.4/dist-packages/cfclient-_modified-py3.4.egg/cfclient/`

And then it goes a little further, but I've got another kind of error, I will digg about and let you know.

**Comment by ataffanel** [comment]
Thanks for the report. So far I have only been testing dev installs, ```pip install -e .```, not yet a real install.

I think we need ```package_data``` to be declared with all the .ui and .json files (the same way we have ```data_files``` for py2exe).

**Comment by krystian-wojtas** [comment]
Yes, I can confirm. Install option `pip install -e .` helps.
