### ISSUE TITLE
Cfloader not able to flash Crazyflie 1

### ISSUE THREAD

**Issue by ataffanel** [bitcraze/crazyflie-clients-python#271]
When trying to flash Crazyflie 1 with ```make PLATFORM=CF1 cload`` we get this error:
```
Restart the Crazyflie you want to bootload in the next
10 seconds ...
Traceback (most recent call last):
File "/usr/local/lib/python3.4/dist-packages/cfclient-2016.4_26_g6285f54-py3.4.egg/cfloader/__init__.py", line 150, in main
if bl.start_bootloader(warm_boot=False):
File "/usr/local/lib/python3.4/dist-packages/cflib-0.1.0-py3.4.egg/cflib/bootloader/__init__.py", line 100, in start_bootloader
started = self._cload.check_link_and_get_info()
File "/usr/local/lib/python3.4/dist-packages/cflib-0.1.0-py3.4.egg/cflib/bootloader/cloader.py", line 240, in check_link_and_get_info
return self._set_address(addr)
File "/usr/local/lib/python3.4/dist-packages/cflib-0.1.0-py3.4.egg/cflib/bootloader/cloader.py", line 258, in _set_address
self.link.cradio.set_address((0xE7,) * 5)
AttributeError: 'RadioDriver' object has no attribute 'cradio'
'RadioDriver' object has no attribute 'cradio'
Traceback (most recent call last):
File "bin/cfloader", line 5, in <module>
main()
File "/usr/local/lib/python3.4/dist-packages/cfclient-2016.4_26_g6285f54-py3.4.egg/cfloader/__init__.py", line 195, in main
bl.close()
File "/usr/local/lib/python3.4/dist-packages/cflib-0.1.0-py3.4.egg/cflib/bootloader/__init__.py", line 253, in close
File "/usr/local/lib/python3.4/dist-packages/cflib-0.1.0-py3.4.egg/cflib/bootloader/cloader.py", line 81, in close
File "/usr/local/lib/python3.4/dist-packages/cflib-0.1.0-py3.4.egg/cflib/crtp/radiodriver.py", line 262, in close
AttributeError: 'NoneType' object has no attribute 'stop'
```

This problem seems to have been created by the work done in bitcraze/crazyflie-lib-python#22. The radio is now hidden under a radio-manager object and should not be accessed directly from outside the way cfloader is doing.

**Comment by ataffanel** [comment]
Tanks for the report. I fixed it by removing the change-address function since I did not find a nice way to integrate it with the new architecture and it is not mandatory anyway (it was just 'nice to have' to allow two people to bootload at the same time).
