### ISSUE TITLE
Cannot launch cfclient

### ISSUE THREAD

**Issue by jchen93nj** [bitcraze/crazyflie-clients-python#369]
Hi there,

I keep running into the error while launching the cfclient:

INFO:cfclient.gui:Disabling STL printouts
INFO:cfclient.utils.input.inputreaders:Input readers: ['linuxjsdev', 'pysdl2']
INFO:cfclient.utils.input.inputreaders:Successfully initialized [linuxjsdev]
INFO:cfclient.utils.input.inputreaders:Could not initialize [pysdl2]: No SDL2 support on Linux
INFO:cfclient.utils.input.inputinterfaces:Found interfaces: ['leapmotion', 'wiimote', 'zmqpull']
INFO:cfclient.utils.input.inputinterfaces:Could not initialize [leapmotion]: Leap Motion library probably not installed (No module named 'leapsdk')
INFO:cfclient.utils.input.inputinterfaces:Could not initialize [wiimote]: Missing cwiid (wiimote) driver No module named 'cwiid'
INFO:cfclient.utils.config:Dist config read from /home/junchen/crazyswarm/crazyflie-clients-python/src/cfclient/configs/config.json
INFO:cfclient.utils.config:Config file read from [/home/junchen/.config/cfclient/config.json]
INFO:cfclient.utils.input.inputinterfaces:Could not initialize [zmqpull]: ZMQ input disabled in config file
WARNING:cfclient.ui.widgets.plotwidget:PyQtGraph (or dependency) failed to import:
Traceback (most recent call last):
  File "/home/junchen/crazyswarm/crazyflie-clients-python/src/cfclient/ui/widgets/plotwidget.py", line 58, in <module>
    import pyqtgraph as pg
  File "/home/junchen/.local/lib/python3.5/site-packages/pyqtgraph/__init__.py", line 19, in <module>
    import numpy  ## pyqtgraph requires numpy
  File "/home/junchen/.local/lib/python3.5/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/home/junchen/.local/lib/python3.5/site-packages/numpy/core/__init__.py", line 91, in <module>
    raise ImportError(msg.format(path))
ImportError: Something is wrong with the numpy installation. While importing we detected an older version of numpy in ['/home/junchen/.local/lib/python3.5/site-packages/numpy']. One method of fixing this is to repeatedly uninstall numpy until none is found, then reinstall this version.

WARNING:cfclient.ui.tabs.locopositioning_tab:PyQtGraph (or dependency) failed to import:
Traceback (most recent call last):
  File "/home/junchen/crazyswarm/crazyflie-clients-python/src/cfclient/ui/tabs/locopositioning_tab.py", line 66, in <module>
    import pyqtgraph as pg
  File "/home/junchen/.local/lib/python3.5/site-packages/pyqtgraph/__init__.py", line 19, in <module>
    import numpy  ## pyqtgraph requires numpy
  File "/home/junchen/.local/lib/python3.5/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/home/junchen/.local/lib/python3.5/site-packages/numpy/core/__init__.py", line 91, in <module>
    raise ImportError(msg.format(path))
ImportError: Something is wrong with the numpy installation. While importing we detected an older version of numpy in ['/home/junchen/.local/lib/python3.5/site-packages/numpy']. One method of fixing this is to repeatedly uninstall numpy until none is found, then reinstall this version.

INFO:cfclient.utils.zmq_param:Biding ZMQ for parameters at tcp://*:1213
INFO:cfclient.utils.zmq_led_driver:Biding ZMQ for LED driverat tcp://*:1214
INFO:cfclient.utils.input:Using device blacklist [(VirtualBox|VMware)]
INFO:cflib.crtp.radiodriver:v99.55 dongle with serial N/A found
Traceback (most recent call last):
  File "/home/junchen/.local/bin/cfclient", line 11, in <module>
    load_entry_point('cfclient', 'console_scripts', 'cfclient')()
  File "/home/junchen/crazyswarm/crazyflie-clients-python/src/cfclient/gui.py", line 159, in main
    main_window = MainUI()
  File "/home/junchen/crazyswarm/crazyflie-clients-python/src/cfclient/ui/main.py", line 324, in __init__
    tab = tabClass(self.tabs, cfclient.ui.pluginhelper)
  File "/home/junchen/crazyswarm/crazyflie-clients-python/src/cfclient/ui/tabs/locopositioning_tab.py", line 469, in __init__
    self._set_up_plots()
  File "/home/junchen/crazyswarm/crazyflie-clients-python/src/cfclient/ui/tabs/locopositioning_tab.py", line 496, in _set_up_plots
    self._plot_xy = PlotWrapper("Top view (X/Y)", "x", "y")
  File "/home/junchen/crazyswarm/crazyflie-clients-python/src/cfclient/ui/tabs/locopositioning_tab.py", line 152, in __init__
    self.widget = pg.PlotWidget(title=title, enableMenu=False)
NameError: name 'pg' is not defined

The error message seems misleading. I uninstalled and reinstalled numpy but nothing helped. Could anyone help me out?

**Comment by ataffanel** [comment]
The numpy loaded is from your local folder, it could be that there is an incompatibility between your linux distribution python and the numpy from pip (i have seen problems with binary packages before). have you tried installing dependencies from linux packages instead?
What OS are you using?

**Comment by knmcguire** [comment]
Is there any update on this? Was the issue resolved?

**Comment by krichardsson** [comment]
Closed due to inactivity
