### ISSUE TITLE
PySDL update breaks Windows build

### ISSUE THREAD

**Issue by ataffanel** [bitcraze/crazyflie-clients-python#433]
PySDL version update from #425 is breaking the windows build. The client prints in the console:
```
Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 14, in run
  File "C:\Python36\lib\site-packages\cx_Freeze\initscripts\Console.py", line 26, in run
  File "bin/cfclient", line 5, in <module>
  File "c:\projects\crazyflie-clients-python\src\cfclient\gui.py", line 99, in main
  File "C:\Python36\lib\site-packages\sdl2\__init__.py", line 5, in <module>
  File "C:\Python36\lib\site-packages\sdl2\audio.py", line 175, in <module>
  File "C:\Python36\lib\site-packages\sdl2\dll.py", line 150, in bind_function
ValueError: Could not find function 'SDL_DequeueAudio' in C:\Program Files (x86)\Crazyflie client\lib\cfclient\third_party\SDL2.dll (SDL2 2.0.4)
```

**Comment by ataffanel** [comment]
Fixed!
