### ISSUE TITLE
Build error with cx_freeze 6.2

### ISSUE THREAD

**Issue by acxz** [bitcraze/crazyflie-clients-python#435]
When building this package I am running with the following error:
`python setup.py build`

```
Traceback (most recent call last):
  File "setup.py", line 102, in <module>
    setup(
  File "/usr/lib/python3.8/site-packages/cx_Freeze/dist.py", line 342, in setup
    distutils.core.setup(**attrs)
  File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.8/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.8/site-packages/cx_Freeze/dist.py", line 217, in run
    freezer.Freeze()
  File "/usr/lib/python3.8/site-packages/cx_Freeze/freezer.py", line 645, in Freeze
    self._WriteModules(fileName, self.finder)
  File "/usr/lib/python3.8/site-packages/cx_Freeze/freezer.py", line 536, in _WriteModules
    sourcePackageDir = os.path.dirname(module.file)
  File "/usr/lib/python3.8/posixpath.py", line 152, in dirname
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by acxz** [comment]
Downstream issue: https://github.com/acxz/pkgbuilds/issues/65

**Comment by acxz** [comment]
Fixed with https://github.com/marcelotduarte/cx_Freeze/pull/695/files

**Comment by knmcguire** [comment]
Could you also contribute this fix to the original repository as well?

**Comment by knmcguire** [comment]
Ah my bad I understand it now. You fixed the original tool that we are using. 

Thanks a lot!
