### ISSUE TITLE
Error while installing Cfclient on Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by santiagorg2401** [bitcraze/crazyflie-clients-python#472]
Hi, I hope you're all well,
I am trying to install the cfclient but I constantly get this error I cannot understand:

```
Collecting cfclient
  Using cached https://files.pythonhosted.org/packages/4a/fe/9164d897f5321dd3ffe0994f3ce741d6b76802fa4d6c2c292238db7b922e/cfclient-2021.1.tar.gz
Collecting pyqt5~=5.15.0 (from cfclient)
  Using cached https://files.pythonhosted.org/packages/6e/86/d715e71771cece0e060f2ebab20f3ded067b08a0927dfb3143530cae8098/PyQt5-5.15.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.6/tokenize.py", line 452, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-build-zjczkj91/pyqt5/setup.py'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-zjczkj91/pyqt5/`
```

The steps I've been following:
```
sudo groupadd plugdev
sudo usermod -a -G plugdev $USER
sudo gedit /etc/udev/rules.d/99-crazyradio.rules
# Crazyradio (normal operation)
SUBSYSTEM=="usb", ATTRS{idVendor}=="1915", ATTRS{idProduct}=="7777", MODE="0664", GROUP="plugdev"
# Bootloader
SUBSYSTEM=="usb", ATTRS{idVendor}=="1915", ATTRS{idProduct}=="0101", MODE="0664", GROUP="plugdev"
sudo gedit /etc/udev/rules.d/99-crazyflie.rules
# cat > /etc/udev/rules.d/99-lps.rules << EOF
SUBSYSTEM=="usb", ATTRS{idVendor}=="0483", ATTRS{idProduct}=="df11", MODE="0664", GROUP="plugdev"
EOF
sudo adduser $USER dialout
sudo udevadm control --reload-rules 
sudo udevadm trigger
sudo apt-get update
sudo apt-get install python3
sudo apt-get install git python3 python3-pip python3-pyqt4 python3-numpy python3-zmq python-pyqt5 python3-pyqt5
sudo apt-get install python3 python3-pip python3-pyqt5 python3-pyqt5.qtsvg
*sudo pip3 install pyusb==1.0.0b2
*sudo pip3 install PyUSB
*sudo pip3 install PyQtGraph
*sudo apt-get install python3-pyqtgraph
*sudo pip3 install PyYAML
sudo apt-get install python3 python3-pip python3-usb idle3
mkdir ~/crazyflie
python3 -m pip install cfclient
```

Something worth to say is that when executing the lines with * I get:
```
The directory '/home/santiagorg2401/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/santiagorg2401/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
```

I may be doing something wrong, so please forgive if it is that, if you have a better way to install all the dependencies or any advice, I'll be more than happy to read it.

Sorry too many edits, I was trying to organize better the code section.

**Comment by knmcguire** [comment]
Hi! 

The rights to the folder has changed due to using` sudo pip3 ...` so now it can only be accessed with root. So either you will need to change the rights of the folder back to you, or you install the cfclient with:

`sudo pip3 install cfclient`

**Comment by santiagorg2401** [comment]
Hi,
So for fresh Ubuntu installations (I constantly erase everything and install again, so I have a list of commands when installing all the things related with Crazyflies), is it better that the following commands to be executed without sudo?

```
*sudo pip3 install PyUSB
*sudo pip3 install PyQtGraph
*sudo pip3 install PyYAML
```
Could you please tell me how to change the rights of the folder back?
I tried changing the permissions of `/usr/local/lib/python3.6/` with chmod but It did not work.

Thank you for taking the time to answer.

**Comment by knmcguire** [comment]
Yes you should not use sudo with pip3, but ones you do it is a bit difficult to get around it. You can uninstall those packes with sudo 

`sudo pip3 uninstall PyUSB PyQtGraph PyYAML`

And install it again with

`pip3 install PyUSB PyQtGraph PyYAML`

Also googling the problem might give you some examples: https://dev.to/elabftw/stop-using-sudo-pip-install-52mn

**Comment by santiagorg2401** [comment]
I did it but still when running `python3 -m pip install cfclient` gives the same error:
`Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-crpzuewm/pyqt5/`, as It says pyqt5 I tried `sudo pip3 uninstall pyqt5`  and then `pip3 uninstall pyqt5` but still the same error.

**Comment by jonasdn** [comment]
Hi @santiagorg2401 !

So lets get to the bottom of this! What is the error message you are currently struggling with?
Is it still about the permissions on your `/home/santiagorg2401/.cache/pip` directory? Could you perhaps go:

```
$ ls -la santiagorg2401/.cache/
$ ls -la santiagorg2401/.cache/pip
$ ls -la santiagorg2401/.cache/http
```
And tell us the output?

@knmcguire is right in that you should try to avoid using sudo, instead specify to pip that you want to install the package and its requirements as a user with:

What does ...
```
$ pip install --user cfclient
```
.. result in? On a clean Ubuntu 20 install, this works fine for me.

**Comment by santiagorg2401** [comment]
Hi @jonasdn 
These are the outputs in order:
1.
```
total 144
drwx------ 29 santiagorg2401 santiagorg2401  4096 mar  1 10:41 .
drwxrwxr-x 39 santiagorg2401 santiagorg2401  4096 mar  4 09:17 ..
drwx------  2 root           root            4096 mar  1 19:26 dconf
drwx------  2 root           root            4096 dic 23 15:50 doc
drwx------  4 santiagorg2401 santiagorg2401  4096 feb 28 19:20 Eclipse
-rw-r--r--  1 santiagorg2401 santiagorg2401 16384 feb 28 13:22 event-sound-cache.tdb.d69f520575e840bd8e06d8cafd966150.x86_64-pc-linux-gnu
drwx------  8 santiagorg2401 santiagorg2401  4096 dic 23 15:37 evolution
drwxr-xr-x  2 santiagorg2401 santiagorg2401 12288 feb 28 20:47 fontconfig
drwx------  6 santiagorg2401 santiagorg2401  4096 feb 23 08:30 gnome-control-center
drwxrwxr-x  8 santiagorg2401 santiagorg2401  4096 ene 18 15:45 gnome-software
drwx------  3 santiagorg2401 santiagorg2401  4096 dic 23 15:44 google-chrome
drwxrwxr-x  2 santiagorg2401 santiagorg2401  4096 mar  2 09:03 gstreamer-1.0
drwxrwxr-x  3 santiagorg2401 santiagorg2401  4096 dic 23 15:37 ibus
drwxrwxr-x  2 santiagorg2401 santiagorg2401  4096 dic 23 15:37 ibus-table
drwxr-xr-x  4 santiagorg2401 santiagorg2401  4096 ene 19 11:38 jedi
drwx------  2 santiagorg2401 santiagorg2401  4096 dic 23 15:37 libgweather
drwxr-xr-x  3 santiagorg2401 santiagorg2401  4096 dic 23 16:40 matplotlib
drwx------  3 santiagorg2401 santiagorg2401  4096 dic 23 15:38 mozilla
drwx------  2 santiagorg2401 santiagorg2401  4096 feb 21 17:03 obexd
drwx------  5 santiagorg2401 santiagorg2401  4096 mar  1 19:47 pip
drwxr-x---  2 santiagorg2401 santiagorg2401  4096 feb 23 10:15 remmina
drwx------  4 santiagorg2401 santiagorg2401  4096 ene 19 13:45 rhythmbox
drwxr-xr-x  2 santiagorg2401 santiagorg2401  4096 feb 21 16:54 shotwell
drwx------  5 santiagorg2401 santiagorg2401  4096 ene 22 14:15 thumbnails
drwx------  4 santiagorg2401 santiagorg2401  4096 ene 19 11:16 thunderbird
drwxr-xr-x  3 santiagorg2401 santiagorg2401  4096 mar  1 10:41 totem
drwx------  2 santiagorg2401 santiagorg2401  4096 dic 23 15:37 ubuntu-report
drwxrwxr-x  2 santiagorg2401 santiagorg2401  4096 dic 23 15:38 update-manager-core
drwx------  2 santiagorg2401 santiagorg2401  4096 feb 21 17:14 wallpaper
drwx------  4 santiagorg2401 santiagorg2401  4096 feb 22 11:24 yelp
-rw-r--r--  1 santiagorg2401 santiagorg2401    11 feb 21 16:48 zeitgeist-vacuum.stamp
```
2.
```
total 20
drwx------  5 santiagorg2401 santiagorg2401 4096 mar  1 19:47 .
drwx------ 29 santiagorg2401 santiagorg2401 4096 mar  1 10:41 ..
drwx------ 18 santiagorg2401 santiagorg2401 4096 mar  1 19:01 http
drwxr-xr-x  2 santiagorg2401 santiagorg2401 4096 mar  1 19:47 selfcheck
drwxr-xr-x 15 santiagorg2401 santiagorg2401 4096 mar  2 11:59 wheels

```
3.
`ls: cannot access '.cache/http': No such file or directory`

**Comment by santiagorg2401** [comment]
If I run `pip3 install --user cfclient`, the output is:
```
Collecting cfclient
  Using cached https://files.pythonhosted.org/packages/4a/fe/9164d897f5321dd3ffe0994f3ce741d6b76802fa4d6c2c292238db7b922e/cfclient-2021.1.tar.gz
Collecting pyqt5~=5.15.0 (from cfclient)
  Using cached https://files.pythonhosted.org/packages/6e/86/d715e71771cece0e060f2ebab20f3ded067b08a0927dfb3143530cae8098/PyQt5-5.15.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.6/tokenize.py", line 452, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-build-5zk1rmkm/pyqt5/setup.py'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-5zk1rmkm/pyqt5/

```

**Comment by jonasdn** [comment]
Thenk you!

According to this Stackoverflow: https://stackoverflow.com/questions/59711301/install-pyqt5-5-14-1-on-linux, there seems like PyQT5 had some issues starting from `5.14.1`. So that older `pip` versions got confused. They recommend either updating your pip to a version > 19:
```
pip3 install --upgrade pip
```
Or making sure to install an earlier version of pyqt5:
```
$ pip3 install --user pyqt5==5.14.0
```

**Comment by jonasdn** [comment]
This any of the above help you with this issue?

**Comment by santiagorg2401** [comment]
Hi, I am sorry for the delay of my answer,
I tried doing so, the cfclient seem to be installed but when trying to run it outputs:
```
Traceback (most recent call last):
  File "/home/santiagorg2401/.local/bin/cfclient", line 5, in <module>
    from cfclient.gui import main
  File "/home/santiagorg2401/.local/lib/python3.6/site-packages/cfclient/gui.py", line 39, in <module>
    from quamash import QSelectorEventLoop
  File "/home/santiagorg2401/.local/lib/python3.6/site-packages/quamash/__init__.py", line 44, in <module>
    QtCore = importlib.import_module(QtModuleName + '.QtCore', package=QtModuleName)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.15' not found (required by /home/santiagorg2401/.local/lib/python3.6/site-packages/PyQt5/QtCore.abi3.so)
```
So I tried to install again pyqt5 as you told me, and shows this:
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
cfclient 2021.1 requires pyqt5~=5.15.0, but you have pyqt5 5.14.0 which is incompatible.
```
As it requires pyqt5 5.15.0, I run: 
`pip3 install --user pyqt5==5.15.0`
And now it works just fine, thank you for the help :+1:

**Comment by jonasdn** [comment]
Excellent!
