### ISSUE TITLE
Error on installation of cfclient using "pip3 install cfclient" on Ubuntu 20.04.05LTS with python3.8.10

### ISSUE THREAD

**Issue by XinLong-Li** [bitcraze/crazyflie-clients-python#655]
The error message is below: 
```
lxl@lxl-Inspiron-3558:~$ pip3 install cfclient
Collecting cfclient
  Using cached cfclient-2022.12-py3-none-any.whl (306 kB)
Collecting qasync~=0.23.0
  Using cached qasync-0.23.0-py3-none-any.whl (13 kB)
Requirement already satisfied: numpy<1.25,>=1.20 in ./.local/lib/python3.8/site-packages (from cfclient) (1.24.2)
Collecting pyserial~=3.5
  Downloading pyserial-3.5-py2.py3-none-any.whl (90 kB)
     |████████████████████████████████| 90 kB 447 kB/s 
Collecting PyQt5-sip>=12.9.0
  Using cached PyQt5_sip-12.11.1-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.whl (361 kB)
Collecting pyqtgraph~=0.11
  Using cached pyqtgraph-0.13.1-py3-none-any.whl (966 kB)
Requirement already satisfied: cflib>=0.1.21 in ./crazyflie-lib-python (from cfclient) (0.1.21)
Requirement already satisfied: PyYAML~=5.3 in /usr/lib/python3/dist-packages (from cfclient) (5.3.1)
Collecting appdirs~=1.4.0
  Using cached appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Collecting pyqt5~=5.15.0
  Using cached PyQt5-5.15.9.tar.gz (3.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 /tmp/tmpo8hzb4qy prepare_metadata_for_build_wheel /tmp/tmpk3erm689
         cwd: /tmp/pip-install-wutg6gvf/pyqt5
    Complete output (31 lines):
    Traceback (most recent call last):
      File "/tmp/tmpo8hzb4qy", line 126, in prepare_metadata_for_build_wheel
        hook = backend.prepare_metadata_for_build_wheel
    AttributeError: module 'sipbuild.api' has no attribute 'prepare_metadata_for_build_wheel'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/tmp/tmpo8hzb4qy", line 280, in <module>
        main()
      File "/tmp/tmpo8hzb4qy", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/tmp/tmpo8hzb4qy", line 130, in prepare_metadata_for_build_wheel
        return _get_wheel_metadata_from_wheel(backend, metadata_directory,
      File "/tmp/tmpo8hzb4qy", line 159, in _get_wheel_metadata_from_wheel
        whl_basename = backend.build_wheel(metadata_directory, config_settings)
      File "/tmp/pip-build-env-s82ut2_f/overlay/lib/python3.8/site-packages/sipbuild/api.py", line 46, in build_wheel
        project = AbstractProject.bootstrap('wheel',
      File "/tmp/pip-build-env-s82ut2_f/overlay/lib/python3.8/site-packages/sipbuild/abstract_project.py", line 87, in bootstrap
        project.setup(pyproject, tool, tool_description)
      File "/tmp/pip-build-env-s82ut2_f/overlay/lib/python3.8/site-packages/sipbuild/project.py", line 585, in setup
        self.apply_user_defaults(tool)
      File "/tmp/pip-install-wutg6gvf/pyqt5/project.py", line 68, in apply_user_defaults
        super().apply_user_defaults(tool)
      File "/tmp/pip-build-env-s82ut2_f/overlay/lib/python3.8/site-packages/pyqtbuild/project.py", line 70, in apply_user_defaults
        super().apply_user_defaults(tool)
      File "/tmp/pip-build-env-s82ut2_f/overlay/lib/python3.8/site-packages/sipbuild/project.py", line 236, in apply_user_defaults
        self.builder.apply_user_defaults(tool)
      File "/tmp/pip-build-env-s82ut2_f/overlay/lib/python3.8/site-packages/pyqtbuild/builder.py", line 69, in apply_user_defaults
        raise PyProjectOptionException('qmake',
    sipbuild.pyproject.PyProjectOptionException
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 /tmp/tmpo8hzb4qy prepare_metadata_for_build_wheel /tmp/tmpk3erm689 Check the logs for full command output.
```

**Comment by XinLong-Li** [comment]
> Sorry for the messy message. I can't put the all message in a code block, but they are a whole, that's all I input in the terminal and the output of terminal.

**Comment by krichardsson** [comment]
I'm not sure why this fails on your machine, but there seems to be a problem with Qt. I tested on my machine and it seems to work as expected (I had a slightly older version of Qt and an upgrade worked without problems).

You could try to uninstall and re-install it as a start to see what happens

``` bash
pip uninstall pyQt5
pip install pyQt5
```

**Comment by XinLong-Li** [comment]
My problem was solved. It turned out that I used the wrong pip. 
I am new to Ubuntu, and I installed a new `Ubuntu20.04.05LTS`, the python included in this system is `python 3.8.10`, and its pip version is `pip 20.0.2`.
```
lxl@lxl-Inspiron-3558:~$ pip3 --version
pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.8)
```

When I run`pip3 install --upgrade pip`, `pip-23.0` was installed in my user directory, but this directory was not added to the `$PATH`. 
```
lxl@lxl-Inspiron-3558:~$ pip3 install --upgrade pip
Collecting pip
  Using cached pip-23.0-py3-none-any.whl (2.1 MB)
Installing collected packages: pip
  WARNING: The scripts pip, pip3 and pip3.8 are installed in '/home/lxl/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed pip-23.0
```
As you can see, there is a warning in the above message. But I am a beginner of Ubuntu, and I didn't realize the importance of that warning. So I got that error described before when I run `pip3 install cfclient`.

When I run 'lxl@lxl-Inspiron-3558:~$ echo $PATH`, I got`/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin`, as we can see that the path '/home/lxl/.local/bin', where my upgraded pip is instlled, is not included in the `$PATH`. So I add '/home/lxl/.local/bin' into `$PATH` through modify the `.bashrc` file in the home directory, and then input `source .bashrc` in the terminal to enable the modification. The problem is solved.
When I run `echo $PATH` again, I got `/home/lxl.local/bin` included.
```
lxl@lxl-Inspiron-3558:~$ echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/lxl.local/bin
```

**Comment by XinLong-Li** [comment]
> I'm not sure why this fails on your machine, but there seems to be a problem with Qt. I tested on my machine and it seems to work as expected (I had a slightly older version of Qt and an upgrade worked without problems).
> 
> You could try to uninstall and re-install it as a start to see what happens
> 
> ```shell
> pip uninstall pyQt5
> pip install pyQt5
> ```

Thank you, sir, my problem was solved. As I described in another comment, it seems not a problem of Qt, it seems a problem of pip, or maybe someone can give a more deep explanation.

**Comment by krichardsson** [comment]
Please see https://github.com/orgs/bitcraze/discussions/545

**Comment by krichardsson** [comment]
@XinLong-Li Did this work out for you? Can we close the issue?
