### ISSUE TITLE
Incompatible Architecture when starting cfclient

### ISSUE THREAD

**Issue by Dwill6978** [bitcraze/crazyflie-clients-python#666]
I successfully downloaded the cfclient software to my Mac running an M1 chip, but everytime I try to run the program I get the following error:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/cfclient", line 5, in <module>
    from cfclient.gui import main
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/cfclient/gui.py", line 40, in <module>
    from qasync import QEventLoop
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/qasync/__init__.py", line 84, in <module>
    QtCore = importlib.import_module(QtModuleName + ".QtCore", package=QtModuleName)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PyQt5/QtCore.abi3.so, 0x0002): tried: '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PyQt5/QtCore.abi3.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PyQt5/QtCore.abi3.so' (no such file), '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PyQt5/QtCore.abi3.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))

I tried diagnosing myself to no avail.  Not sure where to go to solve this issue so any thoughts/advice/fixes would be greatly appreciated. Thanks

**Comment by knmcguire** [comment]
Hi! There are some extra actions to be done for an M1 mac: https://www.bitcraze.io/documentation/repository/crazyflie-clients-python/master/installation/install/#mac Have you done that as well?

**Comment by Dwill6978** [comment]
Yeah, I ran those commands and double-checked my shell was using bash. What was really confusing to me is why the logs were saying I needed arm64 architecture when the instructions said to run the script which installed brew for x86

**Comment by Dwill6978** [comment]
Update: The issue was that PyQt5 was downloaded with x86 architecture so I uninstalled then reinstalled PyQt5 using a arch -arm64 command in the terminal and issue fixed itself

**Comment by knmcguire** [comment]
thanks! I'm keeping this open as this perhaps indicates that we have to add some troubleshooting for the M1s in the documentation. We use issues ourselves as 'pieces of work' and since this implied a possible bug, I didn't transfer it to https://discussions.bitcraze.io/ like I normally would do.

Anyway, if you have any further questions and not necesarely bug indications, please do so at discussions 🙂
