### ISSUE TITLE
Cfclient not getting installed on windows using both build from source and pypi package methods

### ISSUE THREAD

**Issue by darshit-desai** [bitcraze/crazyflie-clients-python#670]
# Errors encountered while installing cfclient on windows 10 enterprise

I tried installing using both methods and it doesn't work,

## 1st method using pypi package, the errors are mentioned below:

```powershell
C:\Users\darshit>pip3 install cfclient
Collecting cfclient
  Downloading cfclient-2023.6-py3-none-any.whl (309 kB)
     ---------------------------------------- 309.1/309.1 kB 19.9 MB/s eta 0:00:00
Requirement already satisfied: cflib>=0.1.23 in d:\crazyflie-lib-python (from cfclient) (0.1.23)
Requirement already satisfied: appdirs~=1.4.0 in c:\users\darshit\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from cfclient) (1.4.4)
Collecting pyzmq~=25.0 (from cfclient)
  Downloading pyzmq-25.1.0-cp311-cp311-win_amd64.whl (1.1 MB)
     ---------------------------------------- 1.1/1.1 MB 18.2 MB/s eta 0:00:00
Requirement already satisfied: pyqtgraph~=0.11 in c:\users\darshit\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from cfclient) (0.12.4)
Collecting PyYAML~=5.3 (from cfclient)
  Downloading PyYAML-5.4.1.tar.gz (175 kB)
     ---------------------------------------- 175.1/175.1 kB ? eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [68 lines of output]
      C:\Users\darshit\AppData\Local\Temp\pip-build-env-2g1nhfk3\overlay\Lib\site-packages\setuptools\config\setupcfg.py:293: _DeprecatedConfig: Deprecated config in `setup.cfg`
      !!

              ********************************************************************************
              The license_file parameter is deprecated, use license_files instead.

              By 2023-Oct-30, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.

              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************

      !!
        parsed = self.parsers.get(option_name, lambda x: x)(value)
      running egg_info
      writing lib3\PyYAML.egg-info\PKG-INFO
      writing dependency_links to lib3\PyYAML.egg-info\dependency_links.txt
      writing top-level names to lib3\PyYAML.egg-info\top_level.txt
      Traceback (most recent call last):
        File "C:\Users\darshit\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\darshit\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\darshit\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\darshit\AppData\Local\Temp\pip-build-env-2g1nhfk3\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\darshit\AppData\Local\Temp\pip-build-env-2g1nhfk3\overlay\Lib\site-packages\setuptools\build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "C:\Users\darshit\AppData\Local\Temp\pip-build-env-2g1nhfk3\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 271, in <module>
        File "C:\Users\darshit\AppData\Local\Temp\pip-build-env-2g1nhfk3\overlay\Lib\site-packages\setuptools\__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\darshit\AppData\Local\Temp\pip-build-env-2g1nhfk3\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "C:\Users\darshit\AppData\Local\Temp\pip-build-env-2g1nhfk3\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\darshit\AppData\Local\Temp\pip-build-env-2g1nhfk3\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\darshit\AppData\Local\Temp\pip-build-env-2g1nhfk3\overlay\Lib\site-packages\setuptools\dist.py", line 1234, in run_command
          super().run_command(command)
        File "C:\Users\darshit\AppData\Local\Temp\pip-build-env-2g1nhfk3\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\darshit\AppData\Local\Temp\pip-build-env-2g1nhfk3\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 314, in run
          self.find_sources()
        File "C:\Users\darshit\AppData\Local\Temp\pip-build-env-2g1nhfk3\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 322, in find_sources
          mm.run()
        File "C:\Users\darshit\AppData\Local\Temp\pip-build-env-2g1nhfk3\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 551, in run
          self.add_defaults()
        File "C:\Users\darshit\AppData\Local\Temp\pip-build-env-2g1nhfk3\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 589, in add_defaults
          sdist.add_defaults(self)
        File "C:\Users\darshit\AppData\Local\Temp\pip-build-env-2g1nhfk3\overlay\Lib\site-packages\setuptools\command\sdist.py", line 104, in add_defaults
          super().add_defaults()
        File "C:\Users\darshit\AppData\Local\Temp\pip-build-env-2g1nhfk3\overlay\Lib\site-packages\setuptools\_distutils\command\sdist.py", line 251, in add_defaults
          self._add_defaults_ext()
        File "C:\Users\darshit\AppData\Local\Temp\pip-build-env-2g1nhfk3\overlay\Lib\site-packages\setuptools\_distutils\command\sdist.py", line 336, in _add_defaults_ext
          self.filelist.extend(build_ext.get_source_files())
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<string>", line 201, in get_source_files
        File "C:\Users\darshit\AppData\Local\Temp\pip-build-env-2g1nhfk3\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip. 
```
## 2nd method using build from source,

```powershell
D:\>git clone https://github.com/bitcraze/crazyflie-clients-python
Cloning into 'crazyflie-clients-python'...
remote: Enumerating objects: 11489, done.
remote: Counting objects: 100% (2709/2709), done.
remote: Compressing objects: 100% (1160/1160), done.
Receiving objects: 100% (11489/11489), 16.71 MiB | 30.12 MiB/s, done.ed 8780

Resolving deltas: 100% (7876/7876), done.

D:\>cd crazyflie-clients-python

D:\crazyflie-clients-python>
D:\crazyflie-clients-python>pip3 install -e .
Obtaining file:///D:/crazyflie-clients-python
  Preparing metadata (setup.py) ... done
Requirement already satisfied: cflib>=0.1.23 in d:\crazyflie-lib-python (from cfclient==2023.6.post3+f290d52) (0.1.23)
Requirement already satisfied: appdirs~=1.4.0 in c:\users\darshit\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from cfclient==2023.6.post3+f290d52) (1.4.4)
Collecting pyzmq~=25.0 (from cfclient==2023.6.post3+f290d52)
  Downloading pyzmq-25.1.0-cp311-cp311-win_amd64.whl (1.1 MB)
     ---------------------------------------- 1.1/1.1 MB 24.5 MB/s eta 0:00:00
Requirement already satisfied: pyqtgraph~=0.11 in c:\users\darshit\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from cfclient==2023.6.post3+f290d52) (0.12.4)
Collecting PyYAML~=5.3 (from cfclient==2023.6.post3+f290d52)
  Using cached PyYAML-5.4.1.tar.gz (175 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [68 lines of output]
      C:\Users\darshit\AppData\Local\Temp\pip-build-env-t0gp7m3i\overlay\Lib\site-packages\setuptools\config\setupcfg.py:293: _DeprecatedConfig: Deprecated config in `setup.cfg`
      !!

              ********************************************************************************
              The license_file parameter is deprecated, use license_files instead.

              By 2023-Oct-30, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.

              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************

      !!
        parsed = self.parsers.get(option_name, lambda x: x)(value)
      running egg_info
      writing lib3\PyYAML.egg-info\PKG-INFO
      writing dependency_links to lib3\PyYAML.egg-info\dependency_links.txt
      writing top-level names to lib3\PyYAML.egg-info\top_level.txt
      Traceback (most recent call last):
        File "C:\Users\darshit\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\darshit\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\darshit\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\darshit\AppData\Local\Temp\pip-build-env-t0gp7m3i\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\darshit\AppData\Local\Temp\pip-build-env-t0gp7m3i\overlay\Lib\site-packages\setuptools\build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "C:\Users\darshit\AppData\Local\Temp\pip-build-env-t0gp7m3i\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 271, in <module>
        File "C:\Users\darshit\AppData\Local\Temp\pip-build-env-t0gp7m3i\overlay\Lib\site-packages\setuptools\__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\darshit\AppData\Local\Temp\pip-build-env-t0gp7m3i\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "C:\Users\darshit\AppData\Local\Temp\pip-build-env-t0gp7m3i\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\darshit\AppData\Local\Temp\pip-build-env-t0gp7m3i\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\darshit\AppData\Local\Temp\pip-build-env-t0gp7m3i\overlay\Lib\site-packages\setuptools\dist.py", line 1234, in run_command
          super().run_command(command)
        File "C:\Users\darshit\AppData\Local\Temp\pip-build-env-t0gp7m3i\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\darshit\AppData\Local\Temp\pip-build-env-t0gp7m3i\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 314, in run
          self.find_sources()
        File "C:\Users\darshit\AppData\Local\Temp\pip-build-env-t0gp7m3i\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 322, in find_sources
          mm.run()
        File "C:\Users\darshit\AppData\Local\Temp\pip-build-env-t0gp7m3i\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 551, in run
          self.add_defaults()
        File "C:\Users\darshit\AppData\Local\Temp\pip-build-env-t0gp7m3i\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 589, in add_defaults
          sdist.add_defaults(self)
        File "C:\Users\darshit\AppData\Local\Temp\pip-build-env-t0gp7m3i\overlay\Lib\site-packages\setuptools\command\sdist.py", line 104, in add_defaults
          super().add_defaults()
        File "C:\Users\darshit\AppData\Local\Temp\pip-build-env-t0gp7m3i\overlay\Lib\site-packages\setuptools\_distutils\command\sdist.py", line 251, in add_defaults
          self._add_defaults_ext()
        File "C:\Users\darshit\AppData\Local\Temp\pip-build-env-t0gp7m3i\overlay\Lib\site-packages\setuptools\_distutils\command\sdist.py", line 336, in _add_defaults_ext
          self.filelist.extend(build_ext.get_source_files())
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<string>", line 201, in get_source_files
        File "C:\Users\darshit\AppData\Local\Temp\pip-build-env-t0gp7m3i\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by Cafeynman** [comment]
after digging in this I think the issue is Python 3.10
PyYAML may not support for Python 3.10, if using python==3.8 it will be fine

**Comment by ataffanel** [comment]
I updated dependencies in the master branch, can you please try again to install from source?

**Comment by ataffanel** [comment]
The dev install is not to be installed anymore, did you find that in the documentation? (it was used for building a windows installer for the client, but we have given-up a while ago since it was constantly breaking ...).

As for the commands, they are installed by pip but it does not appear to be in your environment path. This seems to be a user-only install of Python 3.11, I am not sure where pip puts the scripts in that case (pip does create cfclient.exe, cfloader.exe, etc... on Windows).

The list of the script can be seen in setup.py: https://github.com/bitcraze/crazyflie-clients-python/blob/master/setup.py#L86-L89

For example, to run cfloader, you can run `python -m cfloader`

**Comment by darshit-desai** [comment]
Hi I didn't see the Dev install notice in the installation instructions. Rest of it I'm sure it works, I tried the same for Ubuntu and it was able to add the executables to the path, thank you for your help.
