### ISSUE TITLE
CFclient 2023.11 not starting due to QT6 mismatch

### ISSUE THREAD

**Issue by matejkarasek** [bitcraze/crazyflie-clients-python#690]
Hi,
I cannot get to run the latest release (2023.11) on Win 11 with Python 3.11.4 installed via pip.
2023.6 works fine.
Didn't dig deeper into it, but seems to be related to switching to Qt6?

```
UserWarning: Using SDL2 binaries from pysdl2-dll 2.24.0
INFO:cfclient.gui:Disabling STL printouts
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Program Files\Python311\Scripts\cfclient.exe\__main__.py", line 7, in <module>
  File "C:\Program Files\Python311\Lib\site-packages\cfclient\gui.py", line 162, in main
    from .ui.main import MainUI
  File "C:\Program Files\Python311\Lib\site-packages\cfclient\ui\main.py", line 35, in <module>
    from cfclient.ui.tab_toolbox import TabToolbox
  File "C:\Program Files\Python311\Lib\site-packages\cfclient\ui\tab_toolbox.py", line 34, in <module>
    from PyQt6 import QtWidgets
ImportError: DLL load failed while importing QtCore: The specified procedure could not be found.
```

**Comment by knmcguire** [comment]
Hi! hmmm... that's odd. It sounds like the same issue that people see in the VM... https://github.com/bitcraze/crazyflie-clients-python/issues/689

I'm running it on windows 11 as well with python 3.10, and it worked for me. Is it perhaps something that is missing on this list I wonder? https://doc.qt.io/qt-6/linux-requirements.html, but I can't find the windows equivalent

**Comment by knmcguire** [comment]
Ah good one! Perhaps a bit tricky if already a QT 6 version was installed on the computer... would be handy to not have that happen. We should perhaps put in a check on startup that can detect this mismatch and give some kind of error (like reinstalling QT6)

**Comment by knmcguire** [comment]
So I've tried it on a clean venv environment, and it opens without issues, so this is an problem for anybody that have installed the cfclient through the development branch first a while ago and then updates it.

So in that sense this fix should be:
```
pip3 uninstall PyQt6 PyQt6-Qt6 PyQt6-sip cfclient cflib
pip3 install cfclient
```

**Comment by knmcguire** [comment]
Same thing with the bitcraze VM, in a clean install this issue will not happen. I'd still like to be able to handle issues like this though... either as a startup warning or indicating in documentation... so let's keep this issue open for now.

**Comment by faezehmhmdi** [comment]
I have the same issue on Mac
`UserWarning: Using SDL2 binaries from pysdl2-dll 2.24.0
INFO:cfclient.gui:Disabling STL printouts
INFO:cfclient.utils.input.inputreaders:Input readers: ['linuxjsdev', 'pysdl2']
INFO:cfclient.utils.input.inputreaders:Could not initialize [linuxjsdev]: Only supported on Linux
INFO:cfclient.utils.input.inputreaders:Successfully initialized [pysdl2]
INFO:cfclient.utils.input.inputinterfaces:Found interfaces: ['leapmotion', 'wiimote', 'zmqpull']
INFO:cfclient.utils.input.inputinterfaces:Could not initialize [leapmotion]: Leap Motion library probably not installed (No module named 'leapsdk')
INFO:cfclient.utils.input.inputinterfaces:Could not initialize [wiimote]: Missing cwiid (wiimote) driver No module named 'cwiid'
INFO:cfclient.utils.config:Dist config read from /Users/faezeh/crazyflie-clients-python/src/cfclient/configs/config.json
INFO:cfclient.utils.config:Config file read from [/Users/faezeh/Library/Application Support/cfclient/config.json]
INFO:cfclient.utils.input.inputinterfaces:Could not initialize [zmqpull]: ZMQ input disabled in config file
INFO:cfclient.utils.zmq_led_driver:ZMQ led disabled in config file
INFO:cfclient.utils.zmq_param:ZMQ param disabled in config file
INFO:cfclient.gui:If startup fails because of "xcb", install dependency with `sudo apt install libxcb-xinerama0`.
qt.qpa.plugin: Could not find the Qt platform plugin "cocoa" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

zsh: abort      cfclient`

**Comment by kkcjy** [comment]
> I have the same issue on Mac: UserWarning: Using SDL2 binaries from pysdl2-dll 2.24.0 INFO:cfclient.gui:Disabling STL printouts INFO:cfclient.utils.input.inputreaders:Input readers: ['linuxjsdev', 'pysdl2'] INFO:cfclient.utils.input.inputreaders:Could not initialize [linuxjsdev]: Only supported on Linux INFO:cfclient.utils.input.inputreaders:Successfully initialized [pysdl2] INFO:cfclient.utils.input.inputinterfaces:Found interfaces: ['leapmotion', 'wiimote', 'zmqpull'] INFO:cfclient.utils.input.inputinterfaces:Could not initialize [leapmotion]: Leap Motion library probably not installed (No module named 'leapsdk') INFO:cfclient.utils.input.inputinterfaces:Could not initialize [wiimote]: Missing cwiid (wiimote) driver No module named 'cwiid' INFO:cfclient.utils.config:Dist config read from /Users/faezeh/crazyflie-clients-python/src/cfclient/configs/config.json INFO:cfclient.utils.config:Config file read from [/Users/faezeh/Library/Application Support/cfclient/config.json] INFO:cfclient.utils.input.inputinterfaces:Could not initialize [zmqpull]: ZMQ input disabled in config file INFO:cfclient.utils.zmq_led_driver:ZMQ led disabled in config file INFO:cfclient.utils.zmq_param:ZMQ param disabled in config file INFO:cfclient.gui:If startup fails because of "xcb", install dependency with sudo apt install libxcb-xinerama0. qt.qpa.plugin: Could not find the Qt platform plugin "cocoa" in "" This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
> 
> zsh: abort cfclient

I've met the same problem, have you already overcame it?

**Comment by gemenerik** [comment]
> I've met the same problem, have you already overcame it?

Hi! This thread actually isn't about the issue you're describing. As mentioned earlier, it's a different situation. To keep things organized and make sure you get the right help, please open a new issue with all the details. Thanks for understanding!

**Comment by gemenerik** [comment]
Closing this issue since the author fixed the original problem and we haven’t heard any new reports. It looks like the issue was related to pip installing mismatched packages, but directly pip installing our application seems to avoid it. This might just be a limitation of pip. If anyone still runs into this, feel free to comment and we can re-open — but it’s been quiet for a long, long time.
