### ISSUE TITLE
Client not starting on Mac sonoma

### ISSUE THREAD

**Issue by ataffanel** [bitcraze/crazyflie-clients-python#694]
On an apple silicon mac running sonoma (version 14.2.1), with brew on x86 and python 3.11/3.10 the client does not start and stops with this error:
```
===== 2024.01.24 11:01:10 =====
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.11/site-packages/cfclient/gui.py", line 194, in <module>
    main()
  File "/usr/local/lib/python3.11/site-packages/cfclient/gui.py", line 162, in main
    from .ui.main import MainUI
  File "/usr/local/lib/python3.11/site-packages/cfclient/ui/main.py", line 36, in <module>
    import cfclient.ui.tabs
  File "/usr/local/lib/python3.11/site-packages/cfclient/ui/tabs/__init__.py", line 42, in <module>
    from .locopositioning_tab import LocoPositioningTab
  File "/usr/local/lib/python3.11/site-packages/cfclient/ui/tabs/locopositioning_tab.py", line 52, in <module>
    from vispy import scene
  File "/usr/local/lib/python3.11/site-packages/vispy/__init__.py", line 27, in <module>
    from .util import config, set_log_level, keys, sys_info  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/vispy/util/__init__.py", line 14, in <module>
    from . import fonts       # noqa
    ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/vispy/util/fonts/__init__.py", line 13, in <module>
    from ._triage import _load_glyph, list_fonts  # noqa, analysis:ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/vispy/util/fonts/_triage.py", line 14, in <module>
    from ._quartz import _load_glyph, _list_fonts
  File "/usr/local/lib/python3.11/site-packages/vispy/util/fonts/_quartz.py", line 12, in <module>
    from ...ext.cocoapy import cf, ct, quartz, CFRange, CFSTR, CGGlyph, UniChar, \
  File "/usr/local/lib/python3.11/site-packages/vispy/ext/cocoapy.py", line 1288, in <module>
    quartz = cdll.LoadLibrary(util.find_library('quartz'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ctypes/__init__.py", line 454, in LoadLibrary
    return self._dlltype(name)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ctypes/__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: dlopen(Quartz.framework/Quartz, 0x0006): tried: 'Quartz.framework/Quartz' (no such file), '/System/Volumes/Preboot/Cryptexes/OSQuartz.framework/Quartz' (no such file), '/usr/local/lib/Quartz.framework/Quartz' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/lib/Quartz.framework/Quartz' (no such file), '/usr/lib/Quartz.framework/Quartz' (no such file, not in dyld cache), 'Quartz.framework/Quartz' (no such file)
```

A quick search online seems point to a problem with OpenGL.

**Comment by CalvinKoung** [comment]
Hi. why can not navigate to the python3.11 ?

**Comment by knmcguire** [comment]
That depends on which version pf python you are running the cfclient in. If you have python 3.10 then this is different and you'll need to change it to `/python3.10/ `instead

you can check this in your terminal with `python3 --version`

**Comment by knmcguire** [comment]
Also, there is an issue related to this as well on the github vispy repo https://github.com/vispy/vispy/issues/2547

**Comment by knmcguire** [comment]
And there is a PR open for this now: https://github.com/vispy/vispy/pull/2549

**Comment by ataffanel** [comment]
Thanks for the links and for the solution! I will be looking at somehow enable this fix in a version of the client (at least we can link setup.py to the fixed branch from the PR).

**Comment by knmcguire** [comment]
just an fyi for if we'd like to merge this branch at one point, this does not affect the windows 11 and ubuntu  22.04 installs
